name: Remove Untagged Package Versions
description: Removed untagged GitHub Packages versions
inputs:
  token:
    description: A GitHub token with the 'delete:packages' permission.
    required: true
  repository:
    description: Repository name with owner. E.g. actions/checkout
    required: true
    default: ${{ github.repository }}
  package:
    description: Package name that contains the untagged versions you want to delete
    required: true
  dry_run:
    description: Only find untagged versions but do not delete anything
    default: 'false'
outputs: {}
runs:
  using: 'node16'
  main: 'dist/index.js'
