name: 'units-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  run-unit-tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Create new package version
        uses: docker/build-push-action@v4
        with:
          context: test
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/ci-unit-test:run-${{ github.run_number }}
      - name: Update input file to create new layer
        run: date > test/input.txt
      - name: Update package version to produce untagged layer
        uses: docker/build-push-action@v4
        with:
          context: test
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/ci-unit-test:run-${{ github.run_number }}

      - run: yarn install
      - run: yarn test
        env:
          INPUT_REPOSITORY: ${{ github.repository }}
          INPUT_PACKAGE: ci-unit-test
          INPUT_TOKEN: ${{ github.token }}
          INPUT_PERSONAL_ACCOUNT: false

  # test action works running from the graph
  test-action:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Create new package version
        uses: docker/build-push-action@v4
        with:
          context: test
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/ci-action-test:run-${{ github.run_number }}
      - name: Update input file to create new layer
        run: date > test/input.txt
      - name: Update package version to produce untagged layer
        uses: docker/build-push-action@v4
        with:
          context: test
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/ci-action-test:run-${{ github.run_number }}

      - uses: ./
        with:
          repository: ${{ github.repository }}
          package: ci-action-test
          token: ${{ github.token }}
